### ISSUE TITLE
⠀

### ISSUE THREAD

**Issue by diegomrepo** [lcian/codeforces-cli#1]

**Comment by lcian** [comment]
Hey @diegomrepo !
Thanks for the heads up. If this one gets more popular I don't think the duplicate will be too much of an issue. 
But if you have any ideas for a different name, feel free to propose it, we are still in time to change it :)

I am waiting for a contest to test if my approach to bypass Cloudflare works and then I was planning to post about this repo on the CF blog to get some users/issues/PRs.
So I'd be very happy if you want to submit PRs or ideas that we could implement!

**Comment by diegomrepo** [comment]
I've tested in the past Codeforces Round 944, the Cloudflare hack didn't work. Also for some reason there were 2 cookies named `cf_clearance`. Test both, neither worked.
Also noticed, the input, parsing in new problems it's broken (you get all HTML tags in the retrieval), old problems work OK. I think this last problem is already solved by some collaborators' PR that was not merged in the original tool repo.

**Comment by lcian** [comment]
Yeah, I pushed this commit ec225ec23c9c47e1a2880324369c4d5602a8e5ba so that the cf_clearance cookie is correctly added to ~/.cf/session. I will need to test it again but it should work now.

In this other commit d512e278121fd8feb675baf6a1d3dce99468809f I merged the fix for the input parsing from a pr to the original repo. I just tested it on the last contest (1971) and it works correctly, please let me know if you find that it doesn't work for a certain contest so I can fix it.

Also maybe you were using the old binary because I found out that if you use `go install` it will create the binary as $GOPATH/bin/codeforces-cli, as it looks at the name of the module.

**Comment by diegomrepo** [comment]
Alright, I've tested this today. The cookie prompt worked after some minutes (it seems is not instantaneous, it keeps waiting at the beginning sometimes). So this seems to work (good one)
Also there are still some issues with the input generator. Here (https://codeforces.com/problemset/problem/227/B) for example, will leave out the <br> tags.

**Comment by lcian** [comment]
Thanks for testing, and good catch about the input! Should we just replace `<br />` with newlines then?
